import React, { Component } from 'react';
import Slider from "react-slick";
import { Route, Switch } from 'react-router-dom';


var settings = {
	dots: true,
	infinite: true,
	speed: 500,
	slidesToShow: 1,
	slidesToScroll: 1
};

class Lab extends Component {

	constructor(props) {
		super(props);
		this.state = {
		}
	}

	componentDidMount() {

	}

	render() {
		return (

			<div>
				<div className="Header">
					<div>
						<h2>sejal</h2>
					</div>
				</div>

				<div className="Navigation">
					<h5 onClick={() => this.props.history.push('/')}>About</h5>
					<h5 onClick={() => this.props.history.push('/skills')}>Skills</h5>
					<h5 style={{ borderBottom: "3px solid #ed573d", paddingBottom: 5 }} onClick={() => this.props.history.push('/lab')}>Lab</h5>
					<h5 onClick={() => this.props.history.push('/resume')}>Resume</h5>
					<h5 onClick={() => this.props.history.push('/hire')}>Hire</h5>

				</div>

				<div className="Lab">
					{/* <div className="banner">
						<img src={require('../../../images/new/scientist.png')} style={{ height: 200, marginTop: 20 }}></img>
					</div>
 */}


					<div className="Projects">
						<h2>Projects.me</h2>
						<h4 style={{ fontWeight: "lighter", marginTop: 30 }}>A selected list of projects that I have contributed to or have made. Many more can be found out over at my Github profile.</h4>
						<div style={{ width: "75%", marginTop: 30 }}>


							<hr style={{ width: "60%", borderTop: "1px solid #eee" }}></hr>

							<div style={{ margin: "20px 0px" }}>

								<div style={{ padding: 5 }}>
									<div style={{ display: "flex", flexDirection: "row" }}>
										<img src={require('../../../images/icons/upweb.png')} style={{ width: 30, height: 30, marginRight: 10 }}></img>
										<h3> upweb.io </h3>
									</div>
									<p>
										upweb is a Platform as a Service for fast application deployment using git. Developers can instantly create & deploy static / dynamic websites, REST APIs & microservices etc.
										<br /> App created on upweb will be directly assigned a subdomain with a <span>SSL certificate</span>.
									</p>
									<Slider {...settings} style={{ marginTop: 10 }}>
										<div >
											<img className="project-slider" src={require('../../../images/projects/upweb-1.png')} style={{ width: "60%", height: "50%", objectFit: "contain", margin: "10px auto" }} />
										</div>

										<div>
											<img className="project-slider" src={require('../../../images/projects/upweb-2.png')} style={{ width: "60%", height: "50%", objectFit: "contain", margin: "10px auto" }} />
										</div>


										<div>
											<img className="project-slider" src={require('../../../images/projects/upweb-3.png')} style={{ width: "60%", height: "50%", objectFit: "contain", margin: "10px auto" }} />
										</div>
									</Slider>
									<h4><strong> Features</strong></h4>
									<h4> App : <a href="https://upweb.io/#/" target="_blank"> https://upweb.io </a> </h4>
									<ul>
										<li> Easy deployments with git </li>
										<li> Dashboard to view / monitor logs </li>
										<li> SSL certificates for all the hosted apps </li>
									</ul>
									<p><strong> &lt;/&gt;Technology stacks used :-</strong> <span className="span-code"> nodeJS </span> <span className="span-code"> golang </span>  <span className="span-code"> react-redux </span> <span className="span-code"> postgres-SQL </span>  <span className="span-code"> GCP </span></p>
								</div>
							</div>




							<hr style={{ width: "60%", borderTop: "1px solid #eee" }}></hr>

							<div style={{ margin: "20px 0px" }}>

								<div style={{ padding: 5 }}>
									<div style={{ display: "flex", flexDirection: "row" }}>
										<img src={require('../../../images/icons/echo.png')} style={{ width: 30, height: 30, marginRight: 10 }}></img>
										<h3> echo </h3>
									</div>
									<p>
										Simple syslog drain collection service developed to store & manage STDIN STOUT logs generated by containers hosted on upweb.io
									</p>
									<br />
									<h4><strong> Features</strong></h4>
									<ul>
										<li> SYSLOG collection </li>
										<li> Realtime logs </li>
									</ul>
									<p><strong> &lt;/&gt;Technology stacks used :-</strong> <span className="span-code"> golang </span> <span className="span-code"> redis </span>  <span className="span-code"> GCP </span></p>
								</div>
							</div>


							<hr style={{ width: "60%", color: "#e2e2e2" }}></hr>

							<div style={{ margin: "20px 0px" }}>
								<h3>bigNano</h3>

								<div style={{ padding: 5 }}>
									<pre>
										<code>{
											`
	 const bignano = require('bignano');
   const settings = {
			autoScale: true,
			port: process.env.PORT || 3000,
			mongoDB: {
				databaseName: "dbName",
				userName: "userName",
				password: "password",
				host: "ds121212.mlab.com",
				port: "1234",
			},
			middlewares: [],
			models: [{ name: "name", schema: require('./schema') }],
			routes: [{path: '/', model: "name", methods: ["GET", "PUT","POST", "DELETE"], autoGenerate: true }],
			fileStorage: {s3Token: ""  /* You need to be tocstack user to access fileStorage */}	
		};
				
		global.server = new bignano(settings);
				
		server.init();
		const app = server.getAppInstance();
		server.fileStorage('/home/sejal/Personal/node_js/sjljs/index.js', (response) =&gt; {
		console.log(response);
		});
			`
										}

										</code>
									</pre>
									<p>
										bignano is generic CRUD api package , simple intialization sets up CRUD api endpoint and also supports file storage service intergrated with tocstack - Cloud Platform as a Service for fast application deployment using git. Fork
									</p>
								</div>
							</div>

						</div>

					</div>
				</div>

			</div>

		)
	}
}

export default Lab