export default function ResumePage() {
  return (
    <section className="space-y-6">
      <header className="space-y-3">
        <p className="text-xs text-[var(--muted)]"> ~/sejal/resume </p>
        <p className="text-xs max-w-2xl leading-7 text-[var(--muted)]">A concise snapshot of my work and technical background.</p>
      </header>

      <div className="space-y-10">
        <h3 className="text-sm"> Work Experience </h3>
        <article className="border-l border-[var(--border)] pl-4">
          <h2 className="text-sm text-[var(--foreground)]">Supervity</h2>
          <p className="text-xs text-[var(--muted)]">Senior Solution Engineer (Core Team), October 2021 - Present, Hyderabad</p>
          <ul className="mt-2 list-disc space-y-2 pl-5 text-xs text-[var(--muted)]">
            <li>
              Developed a microservice responsible for executing thread-safe raw workflow logic generated by LLMs and integrating with
              Supervity automation platform, enhancing automated workflow capabilities.
            </li>
            <li>Enhanced Supervity Chrome extension to perform complex UI automation and made it enterprise-ready.</li>
            <li>
              Carried out version upgrades on Keycloak, RabbitMQ, and other dependent microservices to solve 100+ security
              vulnerabilities and make the platform enterprise-ready.
            </li>
            <li>
              Revamped automation job scheduling and queuing mechanism in the core platform for better throughput and solved RabbitMQ
              bottlenecks to process over 1200 automation jobs/min.
            </li>
            <li>Developed SaaS plans pricing and subscription flows along with plan provisioning (paid, free-trial, upgrade).</li>
            <li>
              Led restructuring and refactoring of a legacy web app codebase, incorporated modern React flow creation libraries, and
              reduced development cycle from 4 days to 2 days.
            </li>
          </ul>
        </article>

        <article className="border-l border-[var(--border)] pl-4">
          <h2 className="text-sm text-[var(--foreground)]">BrowserStack</h2>
          <p className="text-xs text-[var(--muted)]">Fullstack Engineer (Growth Team), June 2019 - September 2021, Mumbai</p>
          <ul className="mt-2 list-disc space-y-2 pl-5 text-xs text-[var(--muted)]">
            <li>
              Collaborated with 30+ engineers and upgraded Ruby on Rails and Ruby from 4.1.15 to 6.0.3.6 in the core repository,
              resulting in enhanced security and better API performance.
            </li>
            <li>
              Created a detailed guide to streamline future version upgrades and reduce complexity for the engineering team.
            </li>
            <li>
              Helped revamp unit and functional tests CI/CD pipeline and architecture, reducing unit test execution time from ~21 mins
              to ~4 mins and improving CI/CD build time by 85%.
            </li>
            <li>Migrated plan and subscription upgrade journey for end users from Legacy UI (.erb) to React.</li>
            <li>
              Worked closely with product managers and executed A/B experiments to boost online sales for BrowserStack Live and
              Automate products.
            </li>
          </ul>
        </article>

        <article className="border-l border-[var(--border)] pl-4">
          <h2 className="text-sm text-[var(--foreground)]">Techforce.ai</h2>
          <p className="text-xs text-[var(--muted)]">Product Engineer (Core Team), March 2018 - June 2019, Hyderabad</p>
          <ul className="mt-2 list-disc space-y-2 pl-5 text-xs text-[var(--muted)]">
            <li>
              Patched existing Rasa NLP training service with multi-threaded support and improved model training performance from 1 to
              8 models per VM, along with log and error collection for better retraining.
            </li>
            <li>
              Initiated development of chatbot plugin with action widgets, simplifying product onboarding journey and in-app assistance.
            </li>
            <li>Built a teacher-student collaboration platform from scratch with integrated chatbot for OECD.org.</li>
          </ul>
        </article>

        <article className="border-l border-[var(--border)] pl-4">
          <h2 className="text-sm text-[var(--foreground)]">Binarynumbers</h2>
          <p className="text-xs text-[var(--muted)]">Full Stack Engineer, May 2017 - February 2018, Mumbai</p>
          <ul className="mt-2 list-disc space-y-2 pl-5 text-xs text-[var(--muted)]">
            <li>
              Implemented leads management system for DAMAC that synced user tracking events (~50K events/hour) from multiple
              marketing channels, landing pages, HubSpot, and Facebook to build high-probability cohorts for sales teams.
            </li>
            <li>
              Built CMS/website builder for DAMAC Properties Dubai to dynamically create and serve marketing landing pages and
              accelerated mobile pages with page speed under 1.5 seconds using drag and drop.
            </li>
          </ul>
        </article>
      </div>


      <section className="space-y-8" style={{ marginTop: 50 }}>
        <div className="space-y-6">
          <h3 className="text-sm text-[var(--foreground)]">Programming Languages</h3>
          <div className="flex flex-wrap gap-3 text-xs" style={{ fontSize: 10 }}>
            {["nodeJS", "typescript", "ruby", "golang", "python", "bash"].map((item) => (
              <span key={item} className="bg-[var(--surface)] px-4 py-2 text-[var(--foreground)]">
                <b>
                  {item}
                </b>
              </span>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-sm text-[var(--foreground)]">Frameworks</h3>
          <div className="flex flex-wrap gap-3 text-xs" style={{ fontSize: 10 }}>
            {["express", "react", "react-native", "ruby-on-rails", "langchain"].map((item) => (
              <span key={item} className="bg-[var(--surface)] px-4 py-2 text-[var(--foreground)]">
                <b>
                  {item}
                </b>
              </span>
            ))}
          </div>
        </div>

        <div className="space-y-4">
          <h3 className="text-sm text-[var(--foreground)]">Database & Tools</h3>
          <div className="flex flex-wrap gap-3 text-xs" style={{ fontSize: 10 }}>
            {["postgresSQL", "SQL", "mongoDB", "redis", "docker", "nginx", "rabbitmq", "elastic-search", "git", "llm & gpt",  "AWS", "gcp"].map((item) => (
              <span key={item} className="bg-[var(--surface)] px-4 py-2 text-[var(--foreground)]">
                <b>
                  {item}
                </b>
              </span>
            ))}
          </div>
        </div>
        
        <div className="space-y-4">
          <h3 className="text-sm text-[var(--foreground)]">Analytics</h3>
          <div className="flex flex-wrap gap-3 text-xs" style={{ fontSize: 10 }}>
            {["amplitude", "google-analytics", "big-query"].map((item) => (
              <span key={item} className="bg-[var(--surface)] px-4 py-2 text-[var(--foreground)]">
                <b>
                  {item}
                </b>
              </span>
            ))}
          </div>
        </div>
      </section>

      <section className="space-y-4 pt-6">
        <h3 className="text-sm text-[var(--foreground)]">Education</h3>
        <p className="text-sm text-[var(--foreground)]">Bachelor in Electronics and Telecommunication Engineering</p>
        <p className="text-xs text-[var(--muted)]">University of Pune, India, 2012 - 2016</p>
      </section>
    </section>
  );
}
